### ISSUE TITLE
Jump lines

### ISSUE THREAD

**Issue by vitorhpereira** [nopjmp/discord-webhooks#10]
$webhook->username('Bot')->message('Hello, Human!')->send();

I tried < b r > and \n without success.

How can we jump lines?

Thanks.

**Comment by nopjmp** [comment]
Can you give me an example of using the newline character (\n) and it not working?On Feb 12, 2018 1:34 PM, vitorhpereira <notifications@github.com> wrote:$webhook->username('Bot')->message('Hello, Human!')->send();
I tried  and \n without success.
How can we jump lines?
Thanks.

**Comment by vitorhpereira** [comment]
Sure, here: https://d.pr/free/i/yoJivd

---

$webhook->username('Financeiro Bot')->message('Pagamento confirmado. \r \n \r\n a')->send();

**Comment by vitorhpereira** [comment]
Oh sorry, I was using ' and not "

Sorry! All good :D

**Comment by nopjmp** [comment]
That would do it! Have a great rest of your day!On Feb 12, 2018 1:47 PM, vitorhpereira <notifications@github.com> wrote:Oh sorry, I was using ' and not "
Sorry! All good :D
