### ISSUE TITLE
Add line break to message

### ISSUE THREAD

**Issue by tmartin31** [nopjmp/discord-webhooks#16]
Great job on this!

Is it possible to add a line break to a message? I’ve tried adding `\n` but it’s also being included in the output on Discord.

Thanks.

**Comment by nopjmp** [comment]
Can you provide a code sample for how you are trying to add a newline and the reasoning behind what you are trying to accomplish?

**Comment by tmartin31** [comment]
All good. I’d wrapped the message with single quotes. What an idiot.

**Comment by nopjmp** [comment]
No worries! We all make mistakes. Do let me know if you run into problems with my code though <3
