### ISSUE TITLE
Mark Users

### ISSUE THREAD

**Issue by matheuscamarques** [nopjmp/discord-webhooks#18]
Hello, I would like you to think about the following scenario. I want the webhook to refer someone from the group, how can I do that?

input ('user', '@ usernema#123');

**Comment by nopjmp** [comment]
You need to use the backend text <@snowflake> I believe but it's been awhile

**Comment by matheuscamarques** [comment]
can you make an example?

**Comment by fieu** [comment]
@matheuscamarques Google is your friend. Use it.

I just want to get this ticket closed. This is a Discord relation question, not a library issue.

Example:
```
Hello <@738194349963426152>
```
Where `738194349963426152` is the Discord user ID.

Feel free to close this @nopjmp

**Comment by nopjmp** [comment]
I blame email and GitHub for not notifying me. Closing.
