### ISSUE TITLE
README.md Update

### ISSUE THREAD

**Issue by ghost** [nopjmp/discord-webhooks#3]
Since the last push on this repo, you need to update your README.md, it is using `name` instead of `username`.

**Comment by nopjmp** [comment]
I'll update it when I get a chance but I'm curious why a relatively fresh account is contacting about this. Going to use it in a project?On Jun 26, 2017 1:21 PM, Justin <notifications@github.com> wrote:Since the last push on this repo, you need to update your README.md, it is using name instead of username.

**Comment by ghost** [comment]
Wait do you mean that I'm the only one that's contacted about this and yes I am. @nopjmp

**Comment by nopjmp** [comment]
You are the first one! I'll get it updated when I get home.On Jun 26, 2017 2:14 PM, Justin <notifications@github.com> wrote:Wait do you mean that I'm the only one that's contacted about this and yes I am. @nopjmp

**Comment by nopjmp** [comment]
My name is setup correctly afaict. I don't have my name in the README.md file it's only in the LICENSE.md file.

**Comment by ghost** [comment]
`$webhook->name('Bot')->message('Hello, Human!')->embed($embed)->send();`
should be
`$webhook->username('Bot')->message('Hello, Human!')->embed($embed)->send();`

on the README.md

**Comment by nopjmp** [comment]
Oh.. I thought you were talking about the LICENSE. I understand now. I’ll get that fixed up now that I understand the problem.


On June 29, 2017 at 8:31:55 PM, Justin (notifications@github.com) wrote:

$webhook->name('Bot')->message('Hello, Human!')->embed($embed)->send();
should be
$webhook->username('Bot')->message('Hello, Human!')->embed($embed)->send();

**Comment by bennetgallein** [comment]
Maybe add the `require "vendor/autoload.php`, too.

**Comment by nopjmp** [comment]
If you are using composer you should have already done that. It's only a code snippet not a full fledge page example.

**Comment by bennetgallein** [comment]
Sure, but for unexperienced People (like me) it was hard to get it to work. And that is the one point that made it work.

**Comment by nopjmp** [comment]
It's my personal preference to not include that in my README.md file since I'm not a beginner project but a library.
