### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by ghost** [nopjmp/discord-webhooks#5]
Will this library also support on creating webhooks?

**Comment by nopjmp** [comment]
I’ve considered it. The main issue is creating web hooks requires a login token. I just want to keep this library as lean as possible considering what I’m personally using for is just a “webhook” translator. Also you can change the name and avatar per request “I do this” so you don’t need to make multiple webhooks.


On June 29, 2017 at 9:31:43 PM, Justin (notifications@github.com) wrote:

Will this library also support on creating webhooks?

**Comment by ghost** [comment]
Oh I haven't seen the avatar part, I needed it. But hey maybe make a new library that creates webhooks? RestCord is ehh with creating webhooks.

**Comment by nopjmp** [comment]
What’s so “ehh” about RestCord? I will definitely look at making my own, if I need it. It would be a very minimal interface that requires the app to obtain the api key / login token and just provides nice methods to use.


On June 29, 2017 at 9:36:19 PM, Justin (notifications@github.com) wrote:

Oh I haven't seen the avatar part, I needed it. But hey maybe make a new library that creates webhooks? RestCord is ehh with creating webhooks.

**Comment by ghost** [comment]
I had a really hard time creating webhooks with RestCord.. it took me hours to actually build the URL bc RestCord doesn't spit out the webhook to you and I thought it would but it just took me hours to get it to work together. I would like to move onto a new library and DiscordPHP doesn't support webhooks either, but if you do please tell me so I can use it.

**Comment by bennetgallein** [comment]
We are currently working on a API for Discord's API. I have a fork of it on my profile, if you guys want to contribute @nopjmp @developer-variety

**Comment by nopjmp** [comment]
closed due to age
